name: .NET CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: dotnet restore
    - run: dotnet build --no-restore
    - run: dotnet test --no-build
